version: "3"
services:
  db:
    image: 'postgres:9.5.3'
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: 'pguser'
      POSTGRES_PASSWORD: 'supersecret'
      POSTGRES_DB: 'yamsdb'
#    logging:
#      driver: "none"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redisdata:/data

  app_tracker:
    build:
      context: .
      dockerfile: docker/app_tracker/Dockerfile
#    command: "/bin/bash /tracker/start.sh"
    command: "/usr/local/bin/python /tracker/main.py"
    ports:
      - "9988:9988"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  app_recv_btrx:
    build:
      context: .
      dockerfile: docker/app_recv_btrx/Dockerfile
    command: "/bin/bash /recv_btrx/start.sh"
    depends_on:
      - redis
    links:
      - redis

#  app_analyze:
#    build:
#      context: .
#      dockerfile: docker/app_analyze/Dockerfile
#    depends_on:
#      - elasticsearch
#      - kibana
#    links:
#      - elasticsearch
#      - db
#    restart: always
#
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
#    volumes:
#      - ./docker/config-es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#      - ./data/es:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    restart: always
#    environment:
#      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:5.5.0
#    volumes:
#      - ./docker/config-ki/:/usr/share/kibana/config
#    ports:
#      - "5601:5601"
#    links:
#      - elasticsearch
#    restart: always

