---
general:
  production: false
  loglevel: debug

  limit_threads_recv: 5
  limit_threads_analysis: 5

  # highly depends on the power of your CPU and RAM
  limit_tickerdata: 500

  redis:
    host: redis
    port: 6379
    vars:
      hb_tracker: 'heartbeat-tracker'
    chans:
      data_tracker: 'channel-data'
      data_analyzer: 'channel-analyzer'

  database:
    host: db
    port: 5432

  influxdb:
    host: grafinflux
    port: 8086
    db: cryptodb
    usr: adm
    pwd: adm


datatracker:
  exchanges:
    - bittrex
#    - bitfinex


bittrex:
  enabled: true
  short: 'btrx'
  tickers:
    5m: 'fivemin'
    30m: 'thirtymin'
    1h: 'hour' # we have no 4h on bittrex o_O :(
    1d: 'day'
  stake_currency_enabled: true
  stake_currency: 'BTC'
  min_price_usd: 0.003
  max_price_usd: 1
  blacklist:
    - XVG

#  analysis:
#    plugins:
#      - 00_cci14
#      - 01_strat1
#      - 02_strat2


#
#bifinex:
#  enabled: true
#  short: 'btfi'
#  stake_currency_enabled: true
#  stake_currency: 'USD'
#  min_price_usd: 0.003
#  max_price_usd: 1
#  blacklist:
#    - NEO
