---
general:
  production: false
  loglevel: debug

  limit_threads_recv: 5
  limit_threads_analysis: 5

  redis:
    host: redis
    port: 6379
    chans:
      db_heartbeat: 'channel-db-hb'
      db_heartbeat_ctrl: 'channel-db-hb-ctrl'
      comm: 'channel-comm'
      data: 'channel-data'

  database:
    host: db
    port: 5432

datatracker:
  exchanges:
    - bittrex
#    - bitfinex

bittrex:
  enabled: true
  short: 'btrx'
  tickers:
    5m: 'fivemin'
    30m: 'thirtymin'
    1h: 'hour' # we have no 4h on bittrex o_O :(
    1d: 'day'
  stake_currency_enabled: true
  stake_currency: 'BTC'
  min_price_usd: 0.003
  max_price_usd: 1
  blacklist:
    - XVG
  analysis:
    plugins:
      - 00_cci14
      - 01_strat1
      - 02_strat2


#
#bifinex:
#  enabled: true
#  short: 'btfi'
#  stake_currency_enabled: true
#  stake_currency: 'USD'
#  min_price_usd: 0.003
#  max_price_usd: 1
#  blacklist:
#    - NEO
