---
General:
  production: false
  loglevel: debug

  limit_threads_recv: 5
  limit_threads_analysis: 5

DataTracker:
  exchanges:
    - bittrex
    - bitfinex

Analysis:
  plugins:
    - 00_cci14
    - 01_strat1
    - 02_strat2

#
# disabled, use filters in kibana
#

#bittrex:
#  enabled: true
#  short: 'btrx'
#  stake_currency_enabled: true
#  stake_currency: 'BTC'
#  min_price_usd: 0.003
#  max_price_usd: 1
#  blacklist:
#    - XVG
#
#bifinex:
#  enabled: true
#  short: 'btfi'
#  stake_currency_enabled: true
#  stake_currency: 'USD'
#  min_price_usd: 0.003
#  max_price_usd: 1
#  blacklist:
#    - NEO
